export type Product = {
  id: number
  title: string
  category: string
  tag: string | null
  img: string
  gallery: string[]
  desc: string
  features: string[]
  applications: string[]
  materials: string[]
  specifications: { param: string; value: string }[]
}

export const products: Product[] = [
  {
    id: 1,
    title: 'Solid Carbide Drill',
    category: 'Cutting Tools',
    tag: 'Best Seller',
    img: '/images/products/drill-1.jpg',
    gallery: ['/images/products/drill-1.jpg', '/images/products-bg.jpg', '/images/about-hero.jpg'],
    desc: "Mittal's solid carbide drills are engineered for precision hole-making across a wide range of materials. Manufactured from ultra-fine grain carbide substrate and finished with a physical vapour deposition TiAlN coating, these drills deliver outstanding wear resistance, thermal stability and edge retention even at elevated cutting speeds. The optimised helix angle and polished flutes ensure efficient chip evacuation and minimal heat build-up, resulting in superior surface finish quality and hole tolerances as tight as H7.",
    features: [
      'Ultra-fine grain solid carbide substrate for maximum rigidity',
      'TiAlN PVD coating — hardness up to 3500 HV',
      'Optimised 135° split-point geometry — reduces thrust force',
      'Through-coolant option available on Ø3mm and above',
      'Extended tool life vs HSS by up to 8×',
    ],
    applications: [
      'Aerospace structural components and airframe drilling',
      'Automotive engine blocks, cylinder heads and gearboxes',
      'General precision engineering and job shops',
      'Medical implant and instrument manufacturing',
      'Mould and die drilling in hardened steel',
      'Oil & gas downhole component fabrication',
    ],
    materials: [
      'Carbon and alloy steels (up to 1200 N/mm²)',
      'Hardened steels (up to 60 HRC)',
      'Stainless steels — austenitic and duplex',
      'Cast iron — grey, nodular and compacted graphite',
      'Aluminium and aluminium alloys',
      'Titanium alloys (Ti-6Al-4V)',
      'Nickel-based superalloys (Inconel 718)',
    ],
    specifications: [
      { param: 'Tool Material', value: 'Solid Carbide (K10–K40 grade)' },
      { param: 'Coating', value: 'TiAlN PVD — 3500 HV' },
      { param: 'Diameter Range', value: '0.5 mm – 16.0 mm' },
      { param: 'Tolerance on Diameter', value: 'h6 / h8' },
      { param: 'Flute Count', value: '2 (standard) / 3 (high-feed)' },
      { param: 'Helix Angle', value: '30° standard / 38° for aluminium' },
      { param: 'Point Angle', value: '135° split-point' },
      { param: 'Overall Length (OAL)', value: '38 mm – 150 mm' },
      { param: 'Shank Type', value: 'Straight / Weldon flat (Ø6mm+)' },
      { param: 'Max Cutting Speed (vc)', value: '80–120 m/min (steel)' },
      { param: 'Max Feed Rate (fz)', value: '0.08–0.25 mm/rev' },
      { param: 'Coolant', value: 'Flood / through-tool / MQL compatible' },
      { param: 'DIN Standard', value: 'DIN 6537 / DIN 6539' },
      { param: 'Country of Origin', value: 'Germany / Japan' },
    ],
  },
  {
    id: 2,
    title: 'Carbide Endmill 4-Flute',
    category: 'Cutting Tools',
    tag: 'Popular',
    img: '/images/products/endmill-1.jpg',
    gallery: ['/images/products/endmill-1.jpg', '/images/products-bg.jpg', '/images/about-hero.jpg'],
    desc: 'Our 4-flute solid carbide endmills are designed for high-productivity peripheral milling, slotting, profiling and finishing on steel, stainless and aluminium. The AlTiN nano-composite coating provides exceptional oxidation resistance up to 900 °C, making these tools ideal for dry machining and high-speed cutting strategies. Variable helix geometry minimises harmonic vibration and chatter, ensuring a consistent Ra surface finish on finished surfaces.',
    features: [
      'AlTiN nano-composite coating — oxidation resistance to 900 °C',
      'Variable helix (35°/38°) for chatter-free cutting',
      'Eccentric relief on all four flanks for extended edge life',
      'Corner radius options: sharp / 0.2 / 0.5 / 1.0 mm',
      'Available in standard, long and extra-long reach variants',
    ],
    applications: [
      'High-speed finishing of mould cavities and cores',
      'Peripheral milling of steel components',
      'Profiling and contouring on CNC machining centres',
      '3D surface machining in aerospace structures',
      'Slotting operations in general engineering',
      'Hard machining up to 65 HRC in tool steels',
    ],
    materials: [
      'Carbon steels and alloy steels',
      'Tool steels (P20, H13, D2 — up to 65 HRC)',
      'Stainless steels (304, 316, 17-4 PH)',
      'Cast iron and compacted graphite iron',
      'Aluminium alloys (6061, 7075)',
      'Fibre-reinforced composites (CFRP)',
      'Titanium (Ti-6Al-4V)',
    ],
    specifications: [
      { param: 'Tool Material', value: 'Solid Carbide (K30 / K40)' },
      { param: 'Coating', value: 'AlTiN nano-composite PVD' },
      { param: 'Flute Count', value: '4' },
      { param: 'Diameter Range', value: '2 mm – 20 mm' },
      { param: 'Shank Diameter', value: 'Equal to cutting diameter' },
      { param: 'Helix Angle', value: '35° / 38° variable' },
      { param: 'Corner Geometry', value: 'Sharp / CR 0.2 / 0.5 / 1.0 mm' },
      { param: 'Overall Length (OAL)', value: '50 mm – 130 mm' },
      { param: 'Max Cutting Speed (vc)', value: '100–200 m/min' },
      { param: 'Max Axial Depth (ap)', value: '1× D slotting / 3× D side' },
      { param: 'Max Radial Depth (ae)', value: '50% D slotting / 10% D finishing' },
      { param: 'Runout Tolerance', value: '≤ 0.003 mm' },
      { param: 'DIN Standard', value: 'DIN 6527 / ISO 1641' },
      { param: 'Country of Origin', value: 'Germany' },
    ],
  },
  {
    id: 3,
    title: 'BT40 Tool Holder',
    category: 'Tooling Systems',
    tag: null,
    img: '/images/products/tool-holder-1.jpg',
    gallery: ['/images/products/tool-holder-1.jpg', '/images/products-bg.jpg', '/images/about-hero.jpg'],
    desc: 'These BT40 ER collet chuck tool holders are precision ground from alloy steel and heat treated for maximum rigidity and long-term dimensional stability. The BT40 taper interface conforms to MAS 403 and ISO 7388 standards, ensuring consistent, reliable seating in all BT40-compatible spindles. Balanced to G2.5 at 25,000 RPM for use in high-speed machining centres.',
    features: [
      'Balanced to G2.5 @ 25,000 RPM for high-speed use',
      'Precision ground taper — contact accuracy ≥ 80%',
      'Alloy steel body, induction hardened and ground',
      'Compatible with all BT40 spindle machines',
      'ER11 / ER16 / ER20 / ER25 / ER32 / ER40 variants',
    ],
    applications: [
      'CNC vertical and horizontal machining centres',
      'High-speed milling and drilling operations',
      'Multi-axis machining and compound angle work',
      'Production tooling in automotive and aerospace',
      'Tool presetting and in-machine tool measurement',
    ],
    materials: [
      'Alloy steels — BT40 shank body',
      'Aluminium alloys — lightweight variants',
      'Titanium — for weight-critical aerospace setups',
    ],
    specifications: [
      { param: 'Spindle Interface', value: 'BT40 (MAS 403 / ISO 7388-1)' },
      { param: 'Collet System', value: 'ER11 / ER16 / ER20 / ER25 / ER32 / ER40' },
      { param: 'Clamping Range (ER32)', value: '2 mm – 20 mm' },
      { param: 'Gauge Length', value: '60 mm / 94 mm / 120 mm' },
      { param: 'Static Runout at Gauge', value: '≤ 0.003 mm' },
      { param: 'Dynamic Runout at 3× D', value: '≤ 0.005 mm' },
      { param: 'Pull-Stud Thread', value: 'M16 (MAS-P40T / DIN 69872A)' },
      { param: 'Balance Grade', value: 'G2.5 @ 25,000 RPM' },
      { param: 'Max RPM', value: '25,000 RPM' },
      { param: 'Body Material', value: 'SCM440 alloy steel — 58 HRC surface' },
      { param: 'Nut Type', value: 'Standard nut / coolant-through nut' },
      { param: 'Weight (ER32 standard)', value: '0.52 kg' },
      { param: 'Standard Compliance', value: 'MAS 403 BT / ISO 7388-1' },
    ],
  },
  {
    id: 4,
    title: 'CCMT Turning Insert',
    category: 'Inserts',
    tag: null,
    img: '/images/products/insert-1.jpg',
    gallery: ['/images/products/insert-1.jpg', '/images/about-hero.jpg', '/images/products-bg.jpg'],
    desc: 'CCMT 09T3 series carbide turning inserts are manufactured from fine-grain tungsten carbide with PVD and CVD multilayer coatings available in a range of grades optimised for steel, stainless steel and cast iron. The 80° diamond shape provides a strong cutting edge and versatility across both finishing and semi-finishing operations on CNC lathes.',
    features: [
      'Grade range: P05–P35, M10–M25, K10–K30',
      'PVD TiAlN for steel finishing / CVD TiCN+Al2O3 for roughing',
      'Precision pressed and ground — tolerances to ISO 1832',
      'Dual-sided design — 4 usable cutting edges per insert',
      'Available in 7 chip-breaker variants',
    ],
    applications: [
      'External longitudinal turning on CNC lathes',
      'Facing and profiling operations',
      'Copy turning and contour turning',
      'Finishing passes on shafts and flanges',
      'Semi-finishing of cast and forged blanks',
      'Turning of hardened steel up to 55 HRC',
    ],
    materials: [
      'Low and medium carbon steel (P10–P30)',
      'Alloy steel and heat-treated steel',
      'Stainless steel — austenitic, martensitic, duplex',
      'Grey and nodular cast iron (K10–K25)',
      'Aluminium alloys — uncoated grade',
      'Hardened steel — 45–65 HRC (CBN grade)',
    ],
    specifications: [
      { param: 'ISO Insert Designation', value: 'CCMT 09T3 04 / 08 / 12' },
      { param: 'Shape', value: 'C — 80° rhombic (diamond)' },
      { param: 'Relief Angle', value: '7° (C-type)' },
      { param: 'Tolerance Class', value: 'M (±0.05 mm on IC and thickness)' },
      { param: 'Inscribed Circle (IC)', value: '9.525 mm' },
      { param: 'Thickness (s)', value: '3.97 mm' },
      { param: 'Corner Radius (rε)', value: '0.4 / 0.8 / 1.2 mm' },
      { param: 'Substrate', value: 'Fine-grain WC-Co' },
      { param: 'Coating (steel grade)', value: 'CVD TiCN + Al2O3 + TiN' },
      { param: 'Coating (finishing grade)', value: 'PVD TiAlN' },
      { param: 'Cutting Edges per Insert', value: '4 (double-sided)' },
      { param: 'Chip-breaker Options', value: 'FF / MF / MM / GM / GH / UR / RP' },
      { param: 'Fixing Method', value: 'Top clamp / Screw-on' },
      { param: 'Standard', value: 'ISO 1832' },
    ],
  },
  {
    id: 5,
    title: 'CBN Grinding Wheel',
    category: 'Abrasives',
    tag: 'Specialty',
    img: '/images/products/grinding-wheel-1.jpg',
    gallery: ['/images/products/grinding-wheel-1.jpg', '/images/products-bg.jpg', '/images/about-hero.jpg'],
    desc: 'Vitrified CBN (cubic boron nitride) grinding wheels from Mittal offer the highest material removal rates achievable in the precision grinding of hardened steels, high-speed steels and aerospace superalloys. The vitrified bond is porous and self-dressing, maintaining consistent wheel profile and surface finish Ra values throughout the wheel life.',
    features: [
      'CBN abrasive — second only to diamond in hardness',
      'Vitrified bond — porous, self-dressing, heat-resistant',
      'Form-trued to custom profiles: straight, dish, cup, 1A1',
      'Concentration: 75C / 100C / 125C (by application)',
      'Operating speeds up to 80 m/s (class SG)',
    ],
    applications: [
      'Cylindrical OD and ID grinding of hardened shafts',
      'Camshaft and crankshaft grinding lines (automotive)',
      'Tool and cutter regrinding',
      'Internal grinding of bearing races',
      'Surface grinding of gauge blocks and precision plates',
      'Flute grinding of HSS and carbide drills and endmills',
    ],
    materials: [
      'Hardened alloy steels (50–65 HRC)',
      'High-speed steels (M2, M35, M42)',
      'Tool steels (D2, H13, P20 hardened)',
      'Bearing steels (52100)',
      'Inconel and Waspaloy superalloys',
      'Chrome-plated surfaces',
    ],
    specifications: [
      { param: 'Abrasive Type', value: 'CBN — vitrified bond (B type)' },
      { param: 'Grit Size Range', value: 'B46 / B64 / B91 / B126 / B181' },
      { param: 'Concentration', value: '75 / 100 / 125' },
      { param: 'Bond Type', value: 'Vitrified (V)' },
      { param: 'Wheel Form', value: '1A1 / 1A8 / 6A2 / 11A2 / 14A1' },
      { param: 'Outer Diameter', value: '100 mm – 500 mm (custom)' },
      { param: 'Bore Diameter', value: 'Custom — H5 tolerance' },
      { param: 'Layer Depth', value: '3 mm / 5 mm / 8 mm' },
      { param: 'Max Operating Speed', value: '45 m/s (standard) / 80 m/s (SG class)' },
      { param: 'Hardness Grade', value: 'H / J / K / L' },
      { param: 'Balancing', value: 'Static balanced — ISO 1940 G1.0' },
      { param: 'Truing Method', value: 'Diamond roll / single-point dresser' },
      { param: 'Standard', value: 'ISO 525 / FEPA B series' },
    ],
  },
  {
    id: 6,
    title: 'Bi-Metal Bandsaw Blade',
    category: 'Saw Blades',
    tag: null,
    img: '/images/products/bandsaw-1.jpg',
    gallery: ['/images/products/bandsaw-1.jpg', '/images/about-hero.jpg', '/images/products-bg.jpg'],
    desc: 'M42 bi-metal bandsaw blades feature an M42 cobalt HSS tooth edge electron beam welded to a flexible alloy steel backing. The M42 grade (8% Co) provides superior red hardness and impact resistance, allowing cutting at higher feed rates with fewer blade breakages.',
    features: [
      'M42 HSS tooth (8% cobalt) — electron beam welded',
      'Variable pitch options: 2/3 / 3/4 / 4/6 / 6/10 TPI',
      'Positive rake geometry (10°) for clean, fast cuts',
      'Set pattern: wavy / raker / alternate',
      'Coil stock or cut-to-join lengths available',
    ],
    applications: [
      'Cutting structural steel sections (I-beam, angle, channel)',
      'Solid round and square bar — up to 400 mm diameter',
      'Tube and pipe cutting — thin-wall to heavy-wall',
      'Bundle cutting of steel bars and profiles',
      'Stainless steel and Inconel bar cutting',
      'Production sawing on horizontal bandsaw machines',
    ],
    materials: [
      'Carbon and alloy steels (up to 1400 N/mm²)',
      'Tool steels and die steels (annealed)',
      'Stainless steels — 304, 316, 2205 duplex',
      'Nickel alloys — Inconel 625, 718',
      'Aluminium alloys and extrusions',
      'Copper and bronze alloys',
    ],
    specifications: [
      { param: 'Tooth Material', value: 'M42 HSS (Co 8%) — electron beam welded' },
      { param: 'Backing Material', value: 'Alloy spring steel — fatigue resistant' },
      { param: 'Width Options', value: '13 / 20 / 27 / 34 / 41 / 54 mm' },
      { param: 'Thickness', value: '0.9 mm / 1.07 mm / 1.27 mm' },
      { param: 'Pitch (TPI)', value: '2/3 / 3/4 / 4/6 / 6/10 / 10/14' },
      { param: 'Rake Angle', value: '0° (standard) / 10° (positive)' },
      { param: 'Set Type', value: 'Raker / Wavy / Alternate' },
      { param: 'Tooth Hardness', value: '66–68 HRC (tooth tip)' },
      { param: 'Tensile Strength (back)', value: '1350 N/mm²' },
      { param: 'Standard Length', value: 'Coil — 30 m / 60 m reels' },
      { param: 'Cutting Speed', value: '30–80 m/min (material dependent)' },
      { param: 'Standard', value: 'ISO 4875 / DIN 8179' },
    ],
  },
  {
    id: 7,
    title: 'Digital Vernier Calliper',
    category: 'Metrology',
    tag: null,
    img: '/images/products/calliper-1.jpg',
    gallery: ['/images/products/calliper-1.jpg', '/images/products-bg.jpg', '/images/about-hero.jpg'],
    desc: "Mittal's digital vernier callipers are manufactured from precision ground stainless steel and feature a large LCD display with 0.01 mm resolution. The IP54 ingress protection rating makes them well-suited to workshop environments where coolant and swarf exposure is unavoidable.",
    features: [
      'IP54 rated — protected against splash water and swarf',
      '0.01 mm resolution / 0.0005" resolution in inch mode',
      'ABS (Absolute) measurement system — no re-zeroing on power-up',
      'Large LCD display — readable in low workshop light',
      'Hardened stainless steel beam and jaws — corrosion resistant',
    ],
    applications: [
      'Measurement of OD, ID, depth and step dimensions',
      'Quality inspection and first-off inspection',
      'Incoming goods and goods-out checking',
      'Toolroom and gauge room measurement',
      'Machine shop dimensional verification',
      'On-machine in-process gauging',
    ],
    materials: [
      'Stainless steel workpieces (OD / ID measurement)',
      'Aluminium and alloy castings',
      'Plastic mouldings and rubber parts',
      'Ground and turned steel components',
    ],
    specifications: [
      { param: 'Measuring Range', value: '0–150 mm / 0–200 mm / 0–300 mm' },
      { param: 'Resolution', value: '0.01 mm / 0.0005"' },
      { param: 'Accuracy', value: '±0.02 mm (0–150 mm) / ±0.03 mm (0–300 mm)' },
      { param: 'Repeatability', value: '0.01 mm' },
      { param: 'Display', value: 'LCD — 4-digit' },
      { param: 'Measuring System', value: 'ABS (Absolute)' },
      { param: 'Modes', value: 'mm / inch — switchable' },
      { param: 'Jaw Depth', value: '40 mm (standard jaw)' },
      { param: 'Depth Rod', value: 'Included — 150 mm models' },
      { param: 'IP Rating', value: 'IP54' },
      { param: 'Battery', value: 'SR44 / 1.55 V — 3,000+ hours' },
      { param: 'Body Material', value: 'Hardened stainless steel' },
      { param: 'Calibration Certificate', value: 'Supplied — NABL traceable' },
      { param: 'Standard', value: 'DIN 862 / ISO 13225' },
    ],
  },
  {
    id: 8,
    title: 'Boring Bar Set',
    category: 'Cutting Tools',
    tag: null,
    img: '/images/products/boring-bar-1.jpg',
    gallery: ['/images/products/boring-bar-1.jpg', '/images/products-bg.jpg', '/images/about-hero.jpg'],
    desc: 'Anti-vibration solid carbide boring bars from Mittal are designed for precision internal diameter (ID) turning on CNC lathes and turning centres. The carbide shank material provides 3× higher stiffness than steel bars, enabling longer overhangs with significantly reduced deflection and chatter.',
    features: [
      'Solid carbide shank — 3× stiffer than steel equivalents',
      'Internal vibration damper on L/D > 6 variants',
      'Accepts CCMT / DCMT / VCMT indexable inserts',
      'Through-coolant supply to cutting edge',
      'Shank tolerance h6 for direct clamping in boring heads',
    ],
    applications: [
      'Internal diameter finishing on CNC turning centres',
      'Deep-bore machining (L/D up to 10×)',
      'Precision bearing housing boring',
      'Hydraulic cylinder and valve body ID turning',
      'Mould and die core pocket finishing',
      'Medical — surgical instrument bore machining',
    ],
    materials: [
      'Carbon and alloy steels',
      'Hardened steels (up to 58 HRC with CBN insert)',
      'Stainless steels — 304, 316L, 17-4 PH',
      'Cast iron — grey and ductile',
      'Aluminium alloys',
      'Titanium alloys',
    ],
    specifications: [
      { param: 'Shank Material', value: 'Solid carbide / steel (short variants)' },
      { param: 'Shank Diameter Range', value: '8 mm – 40 mm' },
      { param: 'Minimum Bore Diameter', value: '10 mm (Ø8 mm shank)' },
      { param: 'L/D Ratio', value: 'Up to 10× D (damped variants)' },
      { param: 'Insert Seat', value: 'CCMT 06 / 09 / DCMT 07 / VCMT 11' },
      { param: 'Coolant', value: 'Through-bore internal supply — 80 bar max' },
      { param: 'Shank Tolerance', value: 'h6' },
      { param: 'Clamping Method', value: 'VDI / BMT / capto / straight shank' },
      { param: 'Surface Finish Achievable', value: 'Ra 0.4 µm (with finishing insert)' },
      { param: 'Boring Direction', value: 'Right-hand (standard) / left-hand' },
      { param: 'Max Cutting Depth (ap)', value: '0.5 – 3.0 mm' },
      { param: 'Standard', value: 'ISO 5609 / DIN 69090' },
    ],
  },
  {
    id: 9,
    title: 'TCT Circular Saw Blade',
    category: 'Saw Blades',
    tag: null,
    img: '/images/products/saw-blade-1.jpg',
    gallery: ['/images/products/saw-blade-1.jpg', '/images/products-bg.jpg', '/images/about-hero.jpg'],
    desc: 'Tungsten carbide tipped (TCT) circular saw blades from Mittal are precision laser-cut from high-strength spring steel plate and tensioned for vibration-free running at rated speed. Carbide tips are silver-brazed at high temperature and ground to a precision tip width of ±0.02 mm.',
    features: [
      'Laser-cut and tensioned spring steel body — vibration-free',
      'Silver-brazed tungsten carbide tips — ±0.02 mm tip precision',
      'Alternate top bevel (ATB) and triple chip grind (TCG) options',
      'Anti-kickback shoulder design on kerf slots',
      'Expansion slots with copper plugs — heat compensation',
    ],
    applications: [
      'Cold sawing of solid steel rounds and squares',
      'Stainless steel tube and profile cutting',
      'Aluminium extrusion and bar cutting',
      'Copper and brass rod cutting',
      'Structural section cutting (I-beam, angle)',
      'Production cold saw machines — high volume cutting',
    ],
    materials: [
      'Mild and structural steel (S235 – S355)',
      'Alloy steels up to 900 N/mm²',
      'Stainless steel — 304, 316, 2205 duplex',
      'Aluminium alloys 6xxx, 7xxx series',
      'Copper and copper alloys (brass, bronze)',
    ],
    specifications: [
      { param: 'Body Material', value: '65Mn spring steel — hardened and tensioned' },
      { param: 'Tip Material', value: 'WC-Co grade K10/K20 carbide' },
      { param: 'Outer Diameter Range', value: '180 mm – 550 mm' },
      { param: 'Bore Diameter', value: '25.4 / 30 / 32 / 40 / 50 mm' },
      { param: 'Kerf Width', value: '1.8 – 3.5 mm' },
      { param: 'Body Thickness', value: '1.4 – 2.8 mm' },
      { param: 'Tooth Count', value: '60 / 80 / 100 / 120 / 140 / 160 z' },
      { param: 'Tooth Geometry', value: 'ATB / TCG / Flat top' },
      { param: 'Rake Angle', value: '0° – 15° (material dependent)' },
      { param: 'Max Operating Speed', value: '4,500 RPM (diameter dependent)' },
      { param: 'Cutting Speed', value: '2,500–5,500 m/min surface speed' },
      { param: 'Standard', value: 'ISO 11065 / EN 847-1' },
    ],
  },
  {
    id: 10,
    title: 'Collet ER32 Set',
    category: 'Tooling Systems',
    tag: null,
    img: '/images/products/collet-1.jpg',
    gallery: ['/images/products/collet-1.jpg', '/images/products-bg.jpg', '/images/about-hero.jpg'],
    desc: "Mittal ER32 collet sets are precision manufactured from through-hardened alloy steel and ground to DIN 6499 tolerances. The 16-piece set covers tool shank diameters from 1 mm to 20 mm in 1 mm steps, making it suitable for all routing, milling and drilling operations requiring fast, accurate tool changes.",
    features: [
      '16-piece set: 1–20 mm in 1 mm increments',
      'Ground to DIN 6499B — runout ≤ 0.008 mm at 3× D',
      'Through-hardened alloy steel — 58–62 HRC',
      'Clamping range: 1 mm per collet size',
      'Suitable for ER32 chucks, collet holders and collet blocks',
    ],
    applications: [
      'Tool clamping in CNC machining centres (ER32 holders)',
      'Routing of wood, composites and aluminium',
      'Precision drilling with carbide drills',
      'Grinding operations — cylindrical grinding',
      'Multi-spindle drilling heads',
      'Collet block workholding on surface grinders',
    ],
    materials: [
      'Carbide endmill and drill shanks',
      'HSS tool shanks',
      'Smooth straight shanks — any material h6 tolerance',
    ],
    specifications: [
      { param: 'Collet Type', value: 'ER32 (ISO 15488 / DIN 6499)' },
      { param: 'Set Range', value: '1 mm – 20 mm (16 pieces, 1 mm steps)' },
      { param: 'Clamping Range per Collet', value: '1 mm (e.g. ER32-10 clamps 9–10 mm)' },
      { param: 'Runout Accuracy', value: '≤ 0.008 mm TIR at 3× D (DIN B grade)' },
      { param: 'Collet Length', value: '40 mm (ER32 standard)' },
      { param: 'Taper Angle', value: '8° (ER standard)' },
      { param: 'Nut Thread', value: 'M40 × 1.5' },
      { param: 'Body Material', value: 'Alloy steel — 58–62 HRC (through-hardened)' },
      { param: 'Surface Finish', value: 'Ground — Ra ≤ 0.4 µm on taper contact' },
      { param: 'Max RPM', value: '30,000 RPM (balanced set)' },
      { param: 'Case', value: 'Foam-lined carrying case included' },
      { param: 'Standard', value: 'ISO 15488 / DIN 6499' },
    ],
  },
  {
    id: 11,
    title: 'Threading Insert Set',
    category: 'Inserts',
    tag: null,
    img: '/images/products/threading-1.jpg',
    gallery: ['/images/products/threading-1.jpg', '/images/about-hero.jpg', '/images/products-bg.jpg'],
    desc: 'Mittal threading inserts for CNC lathes cover the full range of metric (M) and unified (UN) external and internal thread profiles. Manufactured from fine-grain carbide with PVD TiN or TiCN coating, these full-profile inserts generate accurate thread crests and roots in a single pass.',
    features: [
      'Full-profile insert — accurate crest and root in one pass',
      'Metric and unified inch profiles — single kit covers both',
      'PVD TiN / TiCN coating for extended insert life',
      'Radial, flank and modified flank infeed compatible',
      'Right-hand and left-hand thread variants available',
    ],
    applications: [
      'External metric and UNC/UNF thread turning',
      'Internal threading (boring bar mounted)',
      'Pipe threads — NPT, BSP, BSPT, API',
      'Trapezoidal and ACME thread profiles',
      'Multi-start thread turning',
      'Thread chasing and repair on CNC lathes',
    ],
    materials: [
      'Low and medium carbon steels',
      'Alloy steels and heat-treated steels',
      'Stainless steel — 304, 316, 17-4 PH',
      'Aluminium alloys (uncoated polished grade)',
      'Plastics and engineering polymers',
    ],
    specifications: [
      { param: 'Insert System', value: 'Full profile — 3-edge indexable' },
      { param: 'Metric Pitch Range', value: '0.5 / 0.75 / 1.0 / 1.25 / 1.5 / 1.75 / 2.0 / 2.5 / 3.0 mm' },
      { param: 'Inch Pitch Range', value: '8 / 11 / 12 / 16 / 18 / 20 / 24 / 32 / 40 / 56 TPI' },
      { param: 'Thread Form', value: '60° (metric / UN) / 55° (BSW, BSP)' },
      { param: 'Substrate', value: 'Fine-grain WC-Co carbide' },
      { param: 'Coating', value: 'PVD TiN (P05–P20) / PVD TiCN (M10–M25)' },
      { param: 'Insert Shape', value: 'V (60°) — ISO designation 16ER / 16IR' },
      { param: 'Infeed Method', value: 'Radial / Flank / Modified flank' },
      { param: 'Cutting Edges per Insert', value: '3' },
      { param: 'Toolholder Compatibility', value: 'SER / SEL 16 / 20 / 25 mm shank' },
      { param: 'Pipe Thread Options', value: 'NPT / BSP / BSPT / API' },
      { param: 'Standard', value: 'ISO 1832 / ISO 4957' },
    ],
  },
  {
    id: 12,
    title: 'Digital Micrometer',
    category: 'Metrology',
    tag: null,
    img: '/images/products/micrometer-1.jpg',
    gallery: ['/images/products/micrometer-1.jpg', '/images/products-bg.jpg', '/images/about-hero.jpg'],
    desc: "Mittal 0–25 mm digital outside micrometers are precision instruments manufactured with a hardened and ground stainless steel frame and carbide-tipped anvil and spindle. The 0.001 mm resolution LCD readout, combined with an ABS measuring system and ratchet thimble stop, delivers consistent, repeatable measurements with a standardised measuring force of 5–10 N.",
    features: [
      '0.001 mm resolution — direct reading digital LCD',
      'ABS measuring system — no zeroing required on startup',
      'Ratchet thimble stop — consistent 5–10 N measuring force',
      'Carbide-tipped anvil and spindle — wear resistant',
      'RS-232 data output for SPC / CMM integration',
    ],
    applications: [
      'Outside diameter measurement of turned components',
      'Thickness measurement of plates, sheets and blanks',
      'Incoming goods inspection and SPC data collection',
      'Toolroom and calibration laboratory gauging',
      'First-off and last-off inspection on CNC lathes',
      'Precision measurement of ground surfaces',
    ],
    materials: [
      'Steel turned and ground components',
      'Aluminium and alloy parts',
      'Stainless steel shafts and pins',
      'Hardened steel gauges and rollers',
      'Plastic and rubber moulded parts',
    ],
    specifications: [
      { param: 'Measuring Range', value: '0–25 mm (also 25–50 / 50–75 / 75–100 mm)' },
      { param: 'Resolution', value: '0.001 mm / 0.00005"' },
      { param: 'Accuracy', value: '±0.002 mm (at 20 °C)' },
      { param: 'Repeatability', value: '0.001 mm' },
      { param: 'Measuring Force', value: '5 – 10 N (ratchet stop controlled)' },
      { param: 'Anvil / Spindle Tip', value: 'Tungsten carbide — DIN 863' },
      { param: 'Display', value: 'Large 4-digit LCD — backlit option' },
      { param: 'Modes', value: 'mm / inch — switchable' },
      { param: 'Data Output', value: 'RS-232 / USB (optional Bluetooth)' },
      { param: 'Frame Material', value: 'Hardened and chrome-plated steel' },
      { param: 'IP Rating', value: 'IP40' },
      { param: 'Battery', value: 'SR44 × 1 — 2,500+ hours' },
      { param: 'Calibration Certificate', value: 'NABL traceable — supplied' },
      { param: 'Standard', value: 'DIN 863 / ISO 3611' },
    ],
  },
]
