export interface PDFItem {
  url: string;
  image: string;
  title: string;
  desc: string;
  pages?: string;
  size?: string;
  type?: string;
  featured?: boolean;
  cover?: string;
  categories?: string[];
}

export interface Brand {
  name: string;
  slug: string;
  logo: string;
  pdfs: PDFItem[];
}

export const brands: Brand[] = [
  {
    name: "Baker",
    slug: "baker",
    logo: "/images/autho/BAKER.png",
    pdfs: [
      {
        url: "/pdf/baker/BakerCatalog2020.pdf",
        image: "/images/pdfs/baker-preview.jpg",
        title: "Baker Product Catalog",
        desc: "Complete catalog featuring precision measuring instruments and gauges.",
        pages: "48 Pages",
        size: "8 MB",
        type: "PDF",
        featured: true,
        cover: "/images/about-hero.jpg",
        categories: ["Measuring Instruments", "Gauges", "Precision Tools"],
      },
    ],
  },
  {
    name: "Bosch",
    slug: "bosch",
    logo: "/images/autho/bosch.png",
    pdfs: [
      {
        url: "/pdf/bosch-catalog.pdf",
        image: "/images/pdfs/bosch-preview.jpg",
        title: "Bosch Power Tools Catalog",
        desc: "Overview of professional power tools, accessories, and measuring technology.",
        pages: "120+ Pages",
        size: "18 MB",
        type: "PDF",
        featured: false,
        cover: "/images/products-bg.jpg",
        categories: ["Power Tools", "Accessories", "Measuring Tech"],
      },
    ],
  },
  {
    name: "CDBP Tools",
    slug: "cdbp-tools",
    logo: "/images/autho/cdbp.png",
    pdfs: [
      {
        url: "/pdf/cdbp-catalog.pdf",
        image: "/images/pdfs/cdbp-preview.jpg",
        title: "CDBP Tools Catalog",
        desc: "Comprehensive guide to industrial tools and equipment specifications.",
        pages: "36 Pages",
        size: "6 MB",
        type: "PDF",
        featured: false,
        cover: "/images/industries-bg.jpg",
        categories: ["Industrial Tools", "Equipment", "Hand Tools"],
      },
    ],
  },
  {
    name: "Conact",
    slug: "conact",
    logo: "/images/autho/conact.png",
    pdfs: [
      {
        url: "/pdf/conact-catalog.pdf",
        image: "/images/pdfs/conact-preview.jpg",
        title: "Conact Product Guide",
        desc: "Detailed technical specifications and product range details.",
        pages: "24 Pages",
        size: "4 MB",
        type: "PDF",
        featured: false,
        cover: "/images/products-bg.jpg",
        categories: ["Technical Components", "Hardware"],
      },
    ],
  },
  {
    name: "CUMI",
    slug: "cumi",
    logo: "/images/autho/cumi.jpg",
    pdfs: [
      {
        url: "/pdf/cumi/CumiIndustrialCatalog.pdf",
        image: "/images/pdfs/cumi-preview.jpg",
        title: "CUMI Abrasives Catalog",
        desc: "Full collection of bonded, coated, and super-abrasive products.",
        pages: "52 Pages",
        size: "10 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Abrasives", "Grinding Wheels", "Coated Abrasives"],
      },
      {
        url: "/pdf/cumi/CumiRetailCatalogue.pdf",
        image: "/images/pdfs/cumi-preview.jpg",
        title: "CUMI Abrasives Catalog",
        desc: "Full collection of bonded, coated, and super-abrasive products.",
        pages: "52 Pages",
        size: "10 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Abrasives", "Grinding Wheels", "Coated Abrasives"],
      },
    ],
  },
  {
    name: "Deskar",
    slug: "deskar",
    logo: "/images/autho/deskar.webp",
    pdfs: [
      {
        url: "/pdf/deskar-catalog.pdf",
        image: "/images/pdfs/deskar-preview.jpg",
        title: "Deskar Cutting Tools Catalog",
        desc: "High-precision carbide inserts and CNC turning/milling tools.",
        pages: "64 Pages",
        size: "12 MB",
        type: "PDF",
        featured: false,
        cover: "/images/industries-bg.jpg",
        categories: ["Carbide Inserts", "CNC Turning", "Milling Tools"],
      },
    ],
  },
  {
    name: "Fenner",
    slug: "fenner",
    logo: "/images/autho/fenner.jpg",
    pdfs: [
      {
        url: "/pdf/fenner-catalog.pdf",
        image: "/images/pdfs/fenner-preview.jpg",
        title: "Fenner Power Transmission Catalog",
        desc: "Industrial belts, pulleys, couplings, and power transmission drives.",
        pages: "40 Pages",
        size: "7 MB",
        type: "PDF",
        featured: false,
        cover: "/images/products-bg.jpg",
        categories: ["Power Transmission", "Industrial Belts", "Pulleys"],
      },
    ],
  },
  {
    name: "Hea-Rok",
    slug: "hea-rok",
    logo: "/images/autho/hea-rok.png",
    pdfs: [
      {
        url: "/pdf/hea-rok-catalog.pdf",
        image: "/images/pdfs/hea-rok-preview.jpg",
        title: "Hea-Rok Product Directory",
        desc: "Brochure outlining machinery component solutions and specifications.",
        pages: "30 Pages",
        size: "5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Machinery Components", "Hardware"],
      },
    ],
  },
  {
    name: "Insize",
    slug: "insize",
    logo: "/images/autho/insize.jpg",
    pdfs: [
      {
        url: "/pdf/insize-catalog.pdf",
        image: "/images/pdfs/insize-preview.jpg",
        title: "Insize Precision Measurement Catalog",
        desc: "Complete listing of calipers, micrometers, indicators, and height gauges.",
        pages: "80 Pages",
        size: "14 MB",
        type: "PDF",
        featured: false,
        cover: "/images/industries-bg.jpg",
        categories: ["Calipers", "Micrometers", "Indicators", "Gauges"],
      },
    ],
  },
  {
    name: "IPOL",
    slug: "ipol",
    logo: "/images/autho/ipol.jpg",
    pdfs: [
      {
        url: "/pdf/ipol/IPOLIndustrialubricantsGreaseCatalog.pdf",
        image: "/images/pdfs/ipol-preview.jpg",
        title: "IPOL Lubricants & Oils Guide",
        desc: "Industrial oils, metalworking fluids, and specialized lubricants catalog.",
        pages: "28 Pages",
        size: "4.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/products-bg.jpg",
        categories: ["Industrial Lubricants", "Metalworking Fluids", "Oils"],
      },
      {
        url: "/pdf/ipol/IPOLMetalWorkingFluidsCatalog.pdf",
        image: "/images/pdfs/ipol-preview.jpg",
        title: "IPOL Lubricants & Oils Guide",
        desc: "Industrial oils, metalworking fluids, and specialized lubricants catalog.",
        pages: "28 Pages",
        size: "4.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/products-bg.jpg",
        categories: ["Industrial Lubricants", "Metalworking Fluids", "Oils"],
      },
    ],
  },
  {
    name: "JK Super Drive",
    slug: "jk-super-drive",
    logo: "/images/autho/super drive.jpg",
    pdfs: [
      {
        url: "/pdf/jk-super-drive-catalog.pdf",
        image: "/images/pdfs/jk-super-drive-preview.jpg",
        title: "JK Super Drive Files & Tools Catalog",
        desc: "High-grade steel files, drills, and hand tools catalog.",
        pages: "32 Pages",
        size: "5.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Steel Files", "Drills", "Hand Tools"],
      },
    ],
  },
  {
    name: "MEBA",
    slug: "meba",
    logo: "/images/autho/meba.jpg",
    pdfs: [
      {
        url: "/pdf/meba-catalog.pdf",
        image: "/images/pdfs/meba-preview.jpg",
        title: "MEBA Sawing Solutions Catalog",
        desc: "Metal band sawing machines and cutting technology brochure.",
        pages: "22 Pages",
        size: "3.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/industries-bg.jpg",
        categories: ["Sawing Solutions", "Band Saws", "Cutting Machines"],
      },
    ],
  },
  {
    name: "Mitutoyo",
    slug: "mitutoyo",
    logo: "/images/autho/mitutoyo.jpg",
    pdfs: [
      {
        url: "/pdf/mitutoyo-catalog.pdf",
        image: "/images/pdfs/mitutoyo-preview.jpg",
        title: "Mitutoyo Metrology Catalog",
        desc: "World-leading precision measuring tools and dimensional metrology solutions.",
        pages: "150+ Pages",
        size: "22 MB",
        type: "PDF",
        featured: false,
        cover: "/images/products-bg.jpg",
        categories: ["Metrology", "Precision Tools", "Measuring Instruments"],
      },
    ],
  },
  {
    name: "Size Control",
    slug: "sizecontrol",
    logo: "/images/autho/sizecontrol.png",
    pdfs: [
      {
        url: "/pdf/size-control-catalog.pdf",
        image: "/images/pdfs/size-control-preview.jpg",
        title: "Size Control Gauges Catalog",
        desc: "Precision plug gauges, ring gauges, and custom gauging tools.",
        pages: "20 Pages",
        size: "3 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Plug Gauges", "Ring Gauges", "Custom Gauges"],
      },
    ],
  },
  {
    name: "Taparia",
    slug: "taparia",
    logo: "/images/autho/taparia.png",
    pdfs: [
      {
        url: "/pdf/taparia-catalog.pdf",
        image: "/images/pdfs/taparia-preview.jpg",
        title: "Taparia Hand Tools Catalog",
        desc: "Comprehensive manual containing pliers, spanners, screwdrivers, and socket sets.",
        pages: "90 Pages",
        size: "15 MB",
        type: "PDF",
        featured: false,
        cover: "/images/industries-bg.jpg",
        categories: ["Pliers", "Spanners", "Screwdrivers", "Sockets"],
      },
    ],
  },
  {
    name: "Tooling Solutions",
    slug: "tooling-solutions",
    logo: "/images/autho/tooling sol.jpg",
    pdfs: [
      {
        url: "/pdf/tooling-solutions-catalog.pdf",
        image: "/images/pdfs/tooling-solutions-preview.jpg",
        title: "Tooling Solutions Overview",
        desc: "Custom and standard tooling accessories for industrial machining.",
        pages: "34 Pages",
        size: "5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/products-bg.jpg",
        categories: ["Tooling Accessories", "Machining Equipment"],
      },
    ],
  },
  {
    name: "Vikas Machine Tools",
    slug: "vikas-machine-tools",
    logo: "/images/autho/vikash.webp",
    pdfs: [
      {
        url: "/pdf/vikas-machine-tools-catalog.pdf",
        image: "/images/pdfs/vikas-machine-tools-preview.jpg",
        title: "Vikas Machine Tools Catalog",
        desc: "Industrial workshop machinery, spare parts, and equipment directory.",
        pages: "44 Pages",
        size: "7.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Workshop Machinery", "Spare Parts", "Equipment"],
      },
    ],
  },
  {
    name: "WolCut",
    slug: "wolcut",
    logo: "/images/autho/wolcut.png",
    pdfs: [
      {
        url: "/pdf/wolcut-catalog.pdf",
        image: "/images/pdfs/wolcut-preview.jpg",
        title: "WolCut Cutting Tools Catalog",
        desc: "High-performance drill bits, reamers, and specialized metal cutters.",
        pages: "26 Pages",
        size: "4 MB",
        type: "PDF",
        featured: false,
        cover: "/images/industries-bg.jpg",
        categories: ["Drill Bits", "Reamers", "Metal Cutters"],
      },
    ],
  },
  {
    name: "XPS",
    slug: "xps",
    logo: "/images/autho/xps.png",
    pdfs: [
      {
        url: "/pdf/xps-catalog.pdf",
        image: "/images/pdfs/xps-preview.jpg",
        title: "XPS Product Line Catalog",
        desc: "Detailed technical specifications and product features.",
        pages: "18 Pages",
        size: "2.8 MB",
        type: "PDF",
        featured: false,
        cover: "/images/products-bg.jpg",
        categories: ["Product Line", "Technical Specs"],
      },
    ],
  },
  {
    name: "Xtra-Power",
    slug: "xtra-power",
    logo: "/images/autho/xtra-power.png",
    pdfs: [
      {
        url: "/pdf/xtra-power-catalog.pdf",
        image: "/images/pdfs/xtra-power-preview.jpg",
        title: "Xtra-Power Tools & Abrasives Catalog",
        desc: "Heavy-duty power tools, diamond saw blades, and abrasive wheels.",
        pages: "56 Pages",
        size: "9.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Power Tools", "Diamond Blades", "Abrasive Wheels"],
      },
    ],
  },
  {
    name: "Korloy",
    slug: "korloy",
    logo: "/images/autho/korloy.png",
    pdfs: [
      {
        url: "/pdf/korloy/KorloyAerospaceIndustryCatalog.pdf",
        image: "/images/autho/korloy.png",
        title: "Korloy Aerospace Industry Catalog",
        desc: "Cutting tool solutions designed specifically for the aerospace industry.",
        pages: "40 Pages",
        size: "8 MB",
        type: "PDF",
        featured: true,
        cover: "/images/about-hero.jpg",
        categories: ["Aerospace", "Cutting Tools", "Machining"],
      },
      {
        url: "/pdf/korloy/KorloyAutomotiveIndustryCatalog.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Automotive Industry Catalog",
        desc: "High-efficiency tooling solutions for automotive component manufacturing.",
        pages: "36 Pages",
        size: "7.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Automotive", "Cutting Tools", "Machining"],
      },
      {
        url: "/pdf/korloy/KorloyCeramicInserts.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Ceramic Inserts",
        desc: "High-speed ceramic inserts for heat-resistant alloys and hardened steel.",
        pages: "24 Pages",
        size: "5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Ceramic Inserts", "Inserts", "Cutting Tools"],
      },
      {
        url: "/pdf/korloy/KorloyH-StarEndmill.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy H-Star Endmill",
        desc: "High-performance solid carbide endmills for high-speed machining.",
        pages: "20 Pages",
        size: "4 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Endmills", "Solid Carbide", "Milling Tools"],
      },
      {
        url: "/pdf/korloy/KorloyHardToCutMaterialCuttingSolution.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Hard To Cut Material Cutting Solution",
        desc: "Specialized cutting solutions for titanium, Inconel, and difficult materials.",
        pages: "28 Pages",
        size: "6 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Hard Material", "Cutting Solutions", "Tooling"],
      },
      {
        url: "/pdf/korloy/KorloyHexaBlade.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Hexa Blade",
        desc: "Hexagonal 6-corner grooving and parting blades for increased cost-efficiency.",
        pages: "16 Pages",
        size: "3.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Hexa Blade", "Grooving", "Parting Tools"],
      },
      {
        url: "/pdf/korloy/KorloyHoleMakingSolution.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Hole Making Solution",
        desc: "Comprehensive lineup of drills, indexable drills, and reaming tools.",
        pages: "48 Pages",
        size: "10 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Hole Making", "Drilling", "Indexable Drills"],
      },
      {
        url: "/pdf/korloy/KorloyMicroEndmillPCDEndmill.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Micro Endmill (PCD Endmill)",
        desc: "Precision PCD micro endmills for fine micro-machining applications.",
        pages: "18 Pages",
        size: "3.8 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Micro Endmills", "PCD Tools", "Precision Tools"],
      },
      {
        url: "/pdf/korloy/KorloyMoldDieSolution.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Mold & Die Solution",
        desc: "Advanced milling, turning, and drilling solutions for mold and die steel.",
        pages: "32 Pages",
        size: "7 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Mold & Die", "Milling", "Tooling"],
      },
      {
        url: "/pdf/korloy/KorloyPipeIndustryCatalog.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Pipe Industry Catalog",
        desc: "Dedicated cutting tools for pipe machining, scarfing, and threading.",
        pages: "22 Pages",
        size: "4.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Pipe Industry", "Scarfing", "Threading"],
      },
      {
        url: "/pdf/korloy/KorloyRailwayIndustryCatalog.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Railway Industry Catalog",
        desc: "Tooling systems for wheel machining, rail maintenance, and heavy turning.",
        pages: "26 Pages",
        size: "5.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Railway", "Heavy Turning", "Industrial Tools"],
      },
      {
        url: "/pdf/korloy/KorloyRecommendedCuttingConditions.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Recommended Cutting Conditions",
        desc: "Technical parameters, speeds, feeds, and machining reference guide.",
        pages: "50 Pages",
        size: "9 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Technical Guide", "Cutting Parameters", "Reference"],
      },
      {
        url: "/pdf/korloy/KorloySolidEndmillBallnose.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Solid Endmill & Ballnose",
        desc: "Full catalogue of square, radius, and ballnose solid carbide endmills.",
        pages: "64 Pages",
        size: "12 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Solid Endmills", "Ballnose", "Carbide Endmills"],
      },
      {
        url: "/pdf/korloy/KorloySpecialTooling.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Special Tooling",
        desc: "Custom engineered tooling solutions tailored for unique manufacturing requirements.",
        pages: "20 Pages",
        size: "4 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Special Tooling", "Custom Tools", "Engineered Solutions"],
      },
      {
        url: "/pdf/korloy/KorloyThreadingCatalog.pdf",
        image: "/images/pdfs/korloy-preview.jpg",
        title: "Korloy Threading Catalog",
        desc: "High-accuracy thread turning, thread milling, and tapping solutions.",
        pages: "30 Pages",
        size: "6.2 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Threading", "Thread Milling", "Tapping"],
      },
    ],
  },
  // MEBA
  {
    name: "MEBA",
    slug: "meba",
    logo: "/images/autho/meba.jpg",
    pdfs: [
      {
        url: "/pdf/meba/MEBA Bandsaw Blades Catalog.pdf",
        image: "/images/pdfs/meba-preview.jpg",
        title: "MEBA Bandsaw Blades Catalog",
        desc: "High-performance bandsaw blades for metal cutting applications.",
        pages: "22 Pages",
        size: "3.5 MB",
        type: "PDF",
        featured: true,
        cover: "/images/industries-bg.jpg",
        categories: ["Bandsaw Blades", "Sawing Solutions", "Cutting Tools"],
      },
      {
        url: "/pdf/meba/MEBAeco 300A Catalog.pdf",
        image: "/images/pdfs/meba-preview.jpg",
        title: "MEBAeco 300A Catalog",
        desc: "Technical specifications and overview for the MEBAeco 300A sawing system.",
        pages: "16 Pages",
        size: "2.8 MB",
        type: "PDF",
        featured: false,
        cover: "/images/industries-bg.jpg",
        categories: ["MEBAeco 300A", "Band Saws", "Cutting Machines"],
      },
    ],
  },
  {
    name: "Mittal",
    slug: "mittal",
    logo: "/images/autho/mittal.png", // Update logo path if needed
    pdfs: [
      {
        url: "/pdf/mittal/Mittal Brochure.pdf",
        image: "/images/pdfs/mittal-preview.jpg",
        title: "Mittal Brochure",
        desc: "Comprehensive brochure outlining product lines and services.",
        pages: "20 Pages",
        size: "4 MB",
        type: "PDF",
        featured: true,
        cover: "/images/about-hero.jpg",
        categories: ["Brochure", "Industrial Tools", "Overview"],
      },
      {
        url: "/pdf/mittal/MITTAL INDUSTRIAL TOOLS.pdf",
        image: "/images/pdfs/mittal-preview.jpg",
        title: "Mittal Industrial Tools Catalog",
        desc: "Full catalogue of high-grade industrial tools and hardware.",
        pages: "32 Pages",
        size: "6.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Industrial Tools", "Hardware", "Equipment"],
      },
    ],
  },
  // Taparia
  {
    name: "Taparia",
    slug: "taparia",
    logo: "/images/autho/taparia.png",
    pdfs: [
      {
        url: "/pdf/taparia/Taparia Allen Keys Catalog.pdf",
        image: "/images/pdfs/taparia-preview.jpg",
        title: "Taparia Allen Keys Catalog",
        desc: "High-torque hex keys and allen key sets for professional use.",
        pages: "18 Pages",
        size: "3 MB",
        type: "PDF",
        featured: false,
        cover: "/images/industries-bg.jpg",
        categories: ["Allen Keys", "Hex Keys", "Hand Tools"],
      },
      {
        url: "/pdf/taparia/Taparia Screw Driver Bits Catalog.pdf",
        image: "/images/pdfs/taparia-preview.jpg",
        title: "Taparia Screw Driver Bits Catalog",
        desc: "Durable screwdriver bits and power bit accessories catalog.",
        pages: "24 Pages",
        size: "4.2 MB",
        type: "PDF",
        featured: false,
        cover: "/images/industries-bg.jpg",
        categories: ["Screwdriver Bits", "Bits", "Hand Tools"],
      },
      {
        url: "/pdf/taparia/Taparia Spanners Sets Catalog.pdf",
        image: "/images/pdfs/taparia-preview.jpg",
        title: "Taparia Spanners Sets Catalog",
        desc: "Complete range of open-end, ring, and combination spanner sets.",
        pages: "30 Pages",
        size: "5.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/industries-bg.jpg",
        categories: ["Spanner Sets", "Combination Spanners", "Hand Tools"],
      },
    ],
  },
  // YG
  {
    name: "YG",
    slug: "yg-1",
    logo: "/images/autho/yg.png", // Update logo path if needed
    pdfs: [
      {
        url: "/pdf/yg/YG Automotive Industry Catalog.pdf",
        image: "/images/pdfs/yg-preview.jpg",
        title: "YG Automotive Industry Catalog",
        desc: "Cutting tool solutions engineered for the automotive manufacturing sector.",
        pages: "36 Pages",
        size: "7.5 MB",
        type: "PDF",
        featured: true,
        cover: "/images/about-hero.jpg",
        categories: ["Automotive", "Cutting Tools", "Machining"],
      },
      {
        url: "/pdf/yg/YG Chamfreing Tools Catalog.pdf",
        image: "/images/pdfs/yg-preview.jpg",
        title: "YG Chamfering Tools Catalog",
        desc: "High-precision chamfering mills and edge-finishing tools.",
        pages: "20 Pages",
        size: "4 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Chamfering Tools", "Milling", "Precision Tools"],
      },
      {
        url: "/pdf/yg/YG Composite Materials.pdf",
        image: "/images/pdfs/yg-preview.jpg",
        title: "YG Composite Materials Catalog",
        desc: "Specialized router bits and endmills designed for composite materials.",
        pages: "22 Pages",
        size: "4.5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Composites", "Routers", "Specialized Cutting"],
      },
      {
        url: "/pdf/yg/YG Die & Mold Catalog.pdf",
        image: "/images/pdfs/yg-preview.jpg",
        title: "YG Die & Mold Catalog",
        desc: "Advanced milling and finish tooling solutions for die & mold steel.",
        pages: "40 Pages",
        size: "8.2 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Die & Mold", "Milling", "Tooling"],
      },
      {
        url: "/pdf/yg/YG EV Mills Catalog.pdf",
        image: "/images/pdfs/yg-preview.jpg",
        title: "YG EV Mills Catalog",
        desc: "High-performance endmills engineered for electric vehicle component machining.",
        pages: "28 Pages",
        size: "5.8 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["EV Mills", "Endmills", "Machining"],
      },
      {
        url: "/pdf/yg/YG i-Xmill Catalog.pdf",
        image: "/images/pdfs/yg-preview.jpg",
        title: "YG i-Xmill Catalog",
        desc: "Indexable milling tool series for high-speed finish milling.",
        pages: "24 Pages",
        size: "5 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["i-Xmill", "Indexable Milling", "High Speed"],
      },
      {
        url: "/pdf/yg/YG Medical Tool Solution.pdf",
        image: "/images/pdfs/yg-preview.jpg",
        title: "YG Medical Tool Solution",
        desc: "Micro-machining and precision tooling tailored for medical devices.",
        pages: "18 Pages",
        size: "3.8 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Medical Tools", "Precision", "Micro Tooling"],
      },
      {
        url: "/pdf/yg/YG Parting & Grooving.pdf",
        image: "/images/pdfs/yg-preview.jpg",
        title: "YG Parting & Grooving Catalog",
        desc: "High-rigidity parting off and grooving insert systems.",
        pages: "30 Pages",
        size: "6.2 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Parting", "Grooving", "Turning Tools"],
      },
      {
        url: "/pdf/yg/YG Solid Carbide Catalog.pdf",
        image: "/images/pdfs/yg-preview.jpg",
        title: "YG Solid Carbide Catalog",
        desc: "Comprehensive range of solid carbide drills, endmills, and reamers.",
        pages: "52 Pages",
        size: "11 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Solid Carbide", "Drills", "Endmills"],
      },
      {
        url: "/pdf/yg/YG Solid Miniature Turning.pdf",
        image: "/images/pdfs/yg-preview.jpg",
        title: "YG Solid Miniature Turning Catalog",
        desc: "Miniature boring and turning tools designed for Swiss-type automatic lathes.",
        pages: "26 Pages",
        size: "5.1 MB",
        type: "PDF",
        featured: false,
        cover: "/images/about-hero.jpg",
        categories: ["Miniature Turning", "Swiss Lathe", "Boring Tools"],
      },
    ],
  },
];
